* Dr Christine Shafner
Podcast "Spectrum of Health", DrChristinuSchaffner.com
* Anti Retrovirus stuff
Freeze dried Brocolli Sprouts
https://articles.mercola.com/sites/articles/archive/2014/06/30/broccoli-sprout-detox.aspx

Powder?
* Candita summit (Klinghardt and Schaffner) 
** mentioned herb (for himself) ash wa ganda, for sleep and hormone health. 
** Yshield graphite paint, must be grounded.
** Silver-lined curtians, must be grounded
** website y-shield.de
** Belly Armor sheilding products for moms and newborns
** Melotonin, If there is a hangover in the AM, use binders
Zeobind, chlorella,clay and charcoal

https://www.youtube.com/watch?v=ACOan6pO6gg&app=desktop
Klinghardt Product Talk

1:19
Start by lining the gut with things that will bind toxins
Don't want to still the pot without getting stuff out.


** Chlorella's
Around 1:15
50% of the weight of chlorella's is amino acid, nearly the same
as breast milk.  is the ideal amino acid supplement

There is nothing that will come close to this.
Contains: 
minerals
mb12

*** Blogaris

*** Electrolyte bronen
- soaked in electrolyte, content is released into the fluid
- Goes all the way into the cell
- If I could only take one thing for detox for an adult it would be this one.



Thriiive summit #13 day one part2
https://www.youtube.com/watch?v=dyzDbu1hMwk

* Dr K Liver Massage
1:41

* The brain has two paths to detox
- lymph system
- 1:56 can't hear what he said


** EMF 
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2
time 12:01
Dr K Mentioned "powerwatch.com" as a good website which compiles studies.

Mesh shield around bed acts as an antena for the ambient EMF (switch off fuses)
This was quoted around 13:15 at
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2


Random interesting comment around 25:00
"The brain is full of fats and oils"

** Alumimun
- Glycosphate chelates alumimum out of the gut into the brain.
- Aluminum does not show up in hair or urine challange tests or poop.
- After filtering (available in Germany) the blood, the aluminum level was 20x higher than "blood level"
- Aluminum is locked into our system and has to be removed by means other than what we have
  available.
- Aluminum levels 20x higher than the next highest element.
- Have been focusing too much on the mercury and lead.
- Nanoized aluminum comes from the persistant contrails of spraying
-- Studies shown (time 52:51 on the affects of the stuff they are spraying
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2 )
- Detox
-- Citic acid, a couple more
-- Malic acid, mag malate
Lemon Water throughout the day
-- Silica is the main treatment to get al out of the brain.
-- Message to moms is that the focus needs to switch to aluminum, and there is not a single lab in
-- the us that can test it.
** Foot bath
- He likes to use clintro with the foot bath
- Urine levels are way higher after the bio pure foot bath + clintro

** Muscle Testing
The biomedical approach relies on testing.
Muscle testing works when normal tests don't including EMF.

** Parasites
- The main drainage treatment are enamas
- When you treat yeast, you are giving a mild antiparisitic
So you make the worms angry, the affect is not from the yeast but from the bystanders that got whacked.
- Food craving is the craving of the parasites
- The parasite can be a biofilm community\w pathogens and parasite DNA
Not just worms
- .01% of the people who have parasites are diagnosed correctly
- A lagre portion of austic kids have schistosomiasis
- Dr K believes that it is a key component in ausitm
http://www.globalnetwork.org/schistosomiasis
-- Symptoms have to do with the bladder
--- If the kid peas a lot then think of this.

-- Some wierd "rope" unidentified parasite
--- Theory: It's purpose is to eliminate the nano aluminum from chem trails
--- A biofilm community


- "This is my message to the autism community" Parasites are not our enemy, they are here as an 
adatpation to an ever increasing toxic environment.
-- You can look at it two ways
--- Evidence of toxcisity
--- Evidence of life trying to save this child.
--- The body is out of the normal de-tox methods, so the body grows parasites.
- The worms extract metals from the host
-- Observe lead (etc) at concentrations 300x higher than the host.
--- This is a well known way to measure polution in the ochean
---- Check the parasites in divers
- When you threaten or kill a parasite, it will release all the toxins back into the system.
-- Need to establish a metal elimination protocol first
- Concern about the supplement industry, Is the multivitiman feeding the parasite.
- What foods feed the parasite.
- Supository, and enma protocols are used.
-- Try to get them out whole.
-- Just want them to poop. 
--- Don't attempt to kill parasites, unless they have frequent good quality poops.
- Parasites love milk

* Chemtrail
- Has mercury
- They are raining mercury down on us

* Test to diagone HM
- Urine porphrine test from France
- Different porphrine's indicate for different HM
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2
Around 1:47
* Milk enamas
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2
Around 1:39

** CD (clorine dioxide)
Around 1:32
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2
Dr K does not like it oraly, said most do not tolerate it.

** Lipozomal
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2
Around 1:27:45
"Throw it in a blender with phospho lipids"

** Water

Robert Slovak
Around time 31:00
https://www.youtube.com/watch?v=Ba4MEuWxGnA&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=5

remineralize Around and before time 1:38
https://www.youtube.com/watch?v=Ba4MEuWxGnA&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=5

Fresh green juice is one of the best way to alkelize the body

see
www.molecularhydgogeninstitute.com
Concept is for hydrogenated water to be used in healing.


Day Two, Part 5
https://www.youtube.com/watch?v=ziyC_KqqIDE&index=3&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs
Klinghart lecture
* Mercury in Jawbone (days after putting a filling in a sheep)
* IV's 
- Dr K does not like IV's sinec we have the liposomal system
- He likes to inject over the organ.
* Lime Disese
** < 25% of people who have like disease have the bul's eye rash
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2
Around 1:46
** A small amount of people with Lime Disease have joint pain
** Alzhimers
Article by Judy McClassi proves that Alzhimers is Spiroceat in brain
** 80% of kids\w ausitem have lime disease in the brain
No ilness as is as similar to Alzhimers than autism.

There is no autism wo 
 - the sprirocete in the brain,
 - significant toxins in the body
 - wo a significant parasite burden (if the autism has been there a year or two).

Treat all of them together

A lot of Epigenic (distorted protean's) oproblems



* Water 
Don't push water with no minerals and electrolytes
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2
They load the drink, and the kids get thirsty and want more.
Add enough electrolytes until you reach a slight salty taste.


* Being outside
Don't be outside if there are heavy chemtrail activity


* Mom & Dad PTSD
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2
Around 2:23:00
- Moms are all is PTSD, from having to live with an autistic kid, and the disapointmenth that comes
with the Drs., withouh getting any acknolgment of the PTSD and without getting any help from any institution.

- Parents need the same treatment as the kids.

* Nothing works if
these superseed every other intervention
- sleeping in E fields environment
- downwind of a fi eld sprayed by glycosphate

* Sleep
Most common (9/10 times) cause of nighttime waking is sleeping in a electromagnetic env.
During a metal detox progrom the children are a living antenna.
2:49:30
https://www.youtube.com/watch?v=ruiBy_HrHuE&list=PLBd231nWQ0f5_je7gE0KnKN9d0nF-7cJs&index=2

* Rigitity
Think minerals!!
Around 3:12:30

https://www.youtube.com/watch?v=lO4wdCc_wfI
* EFT
People get well de EFT


* Dana Goramn interiew
** Describes a condition called pi ro laur re ah
Not enough B6 & zinc
"China doll syndrom"
White in face
no tan or tan only from the neck down
Night people
hard to get up in the morning.
https://www.youtube.com/watch?v=lO4wdCc_wfI
around 22:44

** Low body temperature
related to thyroid
Heat up the system, baths, hot water etc

* Take Back your power
Exposure levels
https://www.youtube.com/watch?v=O13Uq3x6uec
Around 33:30






